linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - deadcode
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goimports
    - gosec
    - govet
    - ifshort
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/cirocosta/go-monero
  exhaustive:
    default-signifies-exhaustive: true

issues:
  fix: true

run:
  timeout: 5m
  skip-dirs:
    - pkg/levin # needs to be refactored anyway
